detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: 192.168.0.40
  user: mqtt_ha
  password: cFXeDaAe99pViUZPa16E
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
record:
  enabled: true
  retain:
    days: 1
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
      - bus
      - cat
      - dog
    retain:
      default: 14
      mode: active_objects
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false
  height: 1920
  retain:
    default: 10
motion:
  improve_contrast: true
objects:
  track:
    - person
    - car
    - bus
    - dog
    - cat
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.6
      threshold: 0.8
    cat:
      min_area: 5000
      max_area: 100000
      min_score: 0.6
      threshold: 0.8

birdseye:
  restream: true

audio:
  enabled: True

go2rtc:
  streams:
    # see https://docs.frigate.video/configuration/camera_specific#reolink-cameras
    # doorbell:
    #   - "ffmpeg:http://192.168.0.66/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=ERoEFRZ46iMpgaeiFvCo#video=copy#audio=copy#audio=opus"
    #   - rtsp://admin:ERoEFRZ46iMpgaeiFvCo@192.168.0.66:554/h264Preview_01_sub
    # doorbell_sub:
    #   - "ffmpeg:http://192.168.0.66/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=ERoEFRZ46iMpgaeiFvCo"
    doorbell:
      - rtsp://admin:ERoEFRZ46iMpgaeiFvCo@192.168.0.66:554/h264Preview_01_main
      - "ffmpeg:doorbell#audio=opus"
    doorbell_sub:
      - rtsp://admin:ERoEFRZ46iMpgaeiFvCo@192.168.0.66:554/h264Preview_01_sub
      - "ffmpeg:doorbell_sub#audio=opus"
    achterdeur:
      - rtsp://admin:ERoEFRZ46iMpgaeiFvCo@192.168.0.85:554/h264Preview_01_main
      - "ffmpeg:achterdeur#audio=opus"
    achterdeur_sub:
      - rtsp://admin:ERoEFRZ46iMpgaeiFvCo@192.168.0.85:554/h264Preview_01_sub
      - "ffmpeg:achterdeur_sub#audio=opus"
    terras:
      - rtsp://admin:ERoEFRZ46iMpgaeiFvCo@192.168.0.243:554/h264Preview_01_main
      - "ffmpeg:terras#audio=opus"
    terras_sub:
      - rtsp://admin:ERoEFRZ46iMpgaeiFvCo@192.168.0.243:554/h264Preview_01_sub
      - "ffmpeg:terras_sub#audio=opus"
    zwembad:
      - rtsp://admin:ERoEFRZ46iMpgaeiFvCo@192.168.0.54:554/h264Preview_01_main
      - "ffmpeg:zwembad#audio=opus"
    zwembad_sub:
      - rtsp://admin:ERoEFRZ46iMpgaeiFvCo@192.168.0.54:554/h264Preview_01_sub
      - "ffmpeg:zwembad_sub#audio=opus"
    veranda:
      - rtsp://admin:ERoEFRZ46iMpgaeiFvCo@192.168.0.187:554/h264Preview_01_main
      - "ffmpeg:veranda#audio=opus"
    veranda_sub:
      - rtsp://admin:ERoEFRZ46iMpgaeiFvCo@192.168.0.187:554/h264Preview_01_sub
      - "ffmpeg:veranda_sub#audio=opus"
    evabed:
      - rtsp://admin:ERoEFRZ46iMpgaeiFvCo@192.168.0.249:554/h264Preview_01_main
      - "ffmpeg:evabed#audio=opus"
    evabed_sub:
      - rtsp://admin:ERoEFRZ46iMpgaeiFvCo@192.168.0.249:554/h264Preview_01_sub
      - "ffmpeg:evabed_sub#audio=opus"
    noabed:
      - rtsp://admin:ERoEFRZ46iMpgaeiFvCo@192.168.0.94:554/h264Preview_01_main
      - "ffmpeg:noabed#audio=opus"
    noabed_sub:
      - rtsp://admin:ERoEFRZ46iMpgaeiFvCo@192.168.0.94:554/h264Preview_01_sub
      - "ffmpeg:noabed_sub#audio=opus"
    bijkeuken:
      - rtsp://robensteffi:rrdwave260@192.168.0.98:88/videoMain


cameras:

  doorbell:
    ffmpeg:
      inputs:
        # the name here must match the name of the camera in restream
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
    detect:
      width: 640
      height: 480
    objects:
      track:
        - person
        - cat
        - dog
    ui:
      order: 0
      dashboard: true

  achterdeur:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/achterdeur_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/achterdeur
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
      global_args: -hide_banner -loglevel info
    detect:
      fps: 5
      width: 640
      height: 360
    motion:
      mask:
        - 0,360,214,360,161,220,125,144,0,78
        - 640,0,0,0,0,66,640,68
    objects:
      track:
        - person
        - cat
    ui:
      order: 2
      dashboard: true

  terras:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terras_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/terras
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
    detect:
      fps: 5
      width: 640
      height: 480
    motion:
      mask:
        - 467,480,619,78,515,133,365,296,335,480
        - 271,29,640,55,640,0,169,0,0,0,0,120
    objects:
      track:
        - person
        - cat
        - dog
    ui:
      order: 3
      dashboard: true

  zwembad:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/zwembad_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/zwembad
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
      global_args: -hide_banner -loglevel info
    detect:
      fps: 5
      width: 640
      height: 360
    motion:
      mask:
        - 0,142,0,0,640,0,640,129
    objects:
      track:
        - person
        - cat
        - dog
    ui:
      order: 4
      dashboard: true

  veranda:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/veranda_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/veranda
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
      global_args: -hide_banner -loglevel info
    detect:
      fps: 5
      width: 640
      height: 360
    motion:
      mask:
        - 0,0,0,94,640,127,640,0
    objects:
      track:
        - person
        - cat
        - dog
    ui:
      order: 5
      dashboard: true

  evabed:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/evabed_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/evabed
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
    detect:
      fps: 5
      width: 640
      height: 352
    objects:
      track:
        - person
        - cat
    ui:
      order: 8
      dashboard: true
  noabed:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/noabed_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/noabed
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
    detect:
      fps: 5
      width: 640
      height: 360
    motion:
      mask:
        - 171,360,0,360,0,0,218,0
    objects:
      track:
        - person
        - cat
    ui:
      order: 9
      dashboard: true

  bijkeuken:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bijkeuken
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    detect:
      fps: 5
      width: 640
      height: 480
    motion:
      mask:
        - 481,0,640,0,640,184,544,147,344,114,328,111,331,0
    ui:
      order: 7
      dashboard: true
version: 0.14
camera_groups:
  Kids:
    order: 1
    icon: LuPersonStanding
    cameras:
      - evabed
      - noabed
