#  __  __       _         _                   _                
# |  \/  | __ _(_)_ __   | |    _____   _____| | __ _  ___ ___ 
# | |\/| |/ _` | | '_ \  | |   / _ \ \ / / _ \ |/ _` |/ __/ _ \
# | |  | | (_| | | | | | | |__| (_) \ V /  __/ | (_| | (_|  __/
# |_|  |_|\__,_|_|_| |_| |_____\___/ \_/ \___|_|\__,_|\___\___|
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#

title: Thuis

swipe_nav:
  wrap: false
  animate: swipe
  prevent_default: true
  swipe_amount: 30


views:
  - !include '/config/lovelace/home.yaml'
  - !include '/config/lovelace/groundfloor.yaml'
  - !include '/config/lovelace/security.yaml'
  - !include '/config/lovelace/cams.yaml'
  - !include '/config/lovelace/hardware.yaml'
  # new
  #- !include '/config/lovelace/firstfloor.yaml'
  #- !include '/config/lovelace/outdoor.yaml'
  