#################################################################
## Automations that alert when the backups are failing         ##
#################################################################

- alias: Snapshots went stale
  description: "Send a Telegram message when the backups are failing"
  trigger:
    - platform: state
      entity_id: binary_sensor.snapshots_stale
      from: "False"
      to: "True"
  condition: []
  action:
    - service: notify.telegram_rob
      data_template:
        title: "🚨🚨 Snapshots are Stale 🚨🚨"
        message: "Please visit the Hass.io Google Drive Backup add-on status page for details."
