#################################################################
## Automations that handle camera events.                      ##
#################################################################

# - alias: Doods Gardencam scanning
#   description: "Trigger a DOODS scan in case there's movement in front of the camera"
#   trigger:
#     - platform: state
#       entity_id: sensor.gardencam_motion_sensor
#       to: "Detected"
#   action:
#     #- delay: "00:00:04"
#     - service: image_processing.scan
#       entity_id: image_processing.doods_gardencam
#     #- delay: "00:00:05"
#     - service: notify.telegram_rob
#       data:
#         message: "Send image detection"
#         data:
#           photo:
#             - file: /config/www/doods/gardencam_latest.jpg
#               caption: Test scan

- alias: Doods Gardencam scanning
  description: "Trigger a DOODS scan in case there's movement in front of the camera"
  trigger:
    - platform: state
      entity_id: binary_sensor.gardencam_motion_sensor
      to: "on"
  action:
    # manually download the snapshot but wait a bit till it's available
    - delay: "00:00:10"
    - service: shell_command.copy_latest_snapshot_gardencam
    - service: image_processing.scan
      entity_id: image_processing.doods_gardencam_snapshot
    # - service: notify.telegram_rob
    #   data:
    #     message: "Send image detection2"
    #     data:
    #       photo:
    #         - file: /config/www/doods/gardencam_snapshot_latest.jpg
    #           caption: Test scan2

- alias: Doods Babycam scanning
  description: "Trigger a DOODS scan in case there's movement in front of the camera"
  trigger:
    - platform: state
      entity_id: sensor.babycam_motion_sensor
      to: "Detected"
  action:
    #- delay: "00:00:04"
    - service: image_processing.scan
      entity_id: image_processing.doods_babycam
    #- delay: "00:00:05"
    # - service: notify.telegram_rob
    #   data:
    #     message: "Send image detection"
    #     data:
    #       photo:
    #         - file: /config/www/doods/babycam_latest.jpg
    #           caption: Test scan

- alias: Cleanup Doods files
  description: "This removes all older files in the history folder of Doods images, to avoid having a full disk"
  trigger:
    - minutes: 0
      platform: time_pattern
  action:
    service: shell_command.cleanup_processed_images


# TODO
# - alias: "tensorflow driveway"
#   trigger:
#     platform: state
#     entity_id: image_processing.doods_driveway
#   condition:
#     condition: or
#     conditions:
#       - condition: template
#         value_template: "{{ 'car' in state_attr('image_processing.doods_driveway', 'summary') }}"
#       - condition: template
#         value_template: "{{ 'truck' in state_attr('image_processing.doods_driveway', 'summary') }}"
