#   ____          _   _             
#  / ___|__ _ ___| |_(_)_ __   __ _ 
# | |   / _` / __| __| | '_ \ / _` |
# | |__| (_| \__ \ |_| | | | | (_| |
#  \____\__,_|___/\__|_|_| |_|\__, |
#                             |___/ 
#
# 🤖 Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
# Casting Home Assistant to Google Home
#

- alias: Cast HA to Nest display
  description: "Push a stream every 10 minutes to the Google Nest Display in the kitchen"
  trigger:
  - minutes: /10
    platform: time_pattern
  condition:
  - after: "6:00"
    before: "23:30"
    condition: time
  action:
  - data:
      addon: a0d7b954_ssh
      input: bash /config/cast.sh
    service: hassio.addon_stdin