#  ____                   _          _ _ 
# |  _ \  ___   ___  _ __| |__   ___| | |
# | | | |/ _ \ / _ \| '__| '_ \ / _ \ | |
# | |_| | (_) | (_) | |  | |_) |  __/ | |
# |____/ \___/ \___/|_|  |_.__/ \___|_|_|
#
# 🤖 Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
# Doorbell alerts
#

- alias: Notification Sonos - Doorbell Ring
  description: "Say ding dong through the speakers when doorbell rings"
  trigger:
    platform: state
    entity_id: binary_sensor.ring_voordeur_ding
    from: "off"
    to: "on"
  action:
    - service: script.sonos_play_sound
      data:
        mp3_url: "https://home.tigrou.nl/local/sounds/doorbell2.mp3"
        volume: 0.4
        sonos_entity: media_player.living_room
        delay: "00:00:03"
