#   ____               _            
#  / ___| __ _ _ __ __| | ___ _ __  
# | |  _ / _` | '__/ _` |/ _ \ '_ \ 
# | |_| | (_| | | | (_| |  __/ | | |
#  \____|\__,_|_|  \__,_|\___|_| |_|
#
# 🤖 Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
# Automations to control the garden lights
#

- alias: Turn on garden lights
  description: "When it's getting dark and at least after 4 PM, turn on lights in the garden"
  trigger:
    - platform: numeric_state
      entity_id: sensor.lightlevel_living
      below: 50
    # faking this once more since it was already dark
    - platform: time
      at: "06:16:00"
  condition:
    condition: or
    conditions:
      # in the evening
      - condition: and
        conditions:
          - condition: time
            after: "16:00:00"
          - condition: time
            before: "22:55:00"
          - condition: state
            entity_id: input_boolean.enable_automatic_garden_lights
            state: 'on'
          - condition: state
            entity_id: light.buitenlamp_zijdeur
            state: 'off'
      # in the morning
      - condition: and
        conditions:
          - condition: time
            after: "06:15:00"
          - condition: time
            before: "08:55:00"
          - condition: state
            entity_id: input_boolean.enable_automatic_garden_lights
            state: 'on'
          - condition: state
            entity_id: light.buitenlamp_zijdeur
            state: 'off'
          - condition: numeric_state
            entity_id: sensor.lightlevel_living
            below: 50
  action:
    - service: light.turn_on
      data:
        entity_id: light.buitenlamp_zijdeur
    - service: notify.telegram_rob
      data:
        message: "💡 Tuinverlichting aan"

- alias: Turn off garden lights
  description: "Turn off lights in the garden at 11 PM"
  trigger:
    - platform: time
      at: "23:00:00"
    - platform: time
      at: "09:00:00"
    - platform: numeric_state
      entity_id: sensor.lightlevel_living
      above: 30
  condition:
    - condition: state
      entity_id: input_boolean.enable_automatic_garden_lights
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.buitenlamp_zijdeur