#   ____                           _ 
#  / ___| ___ _ __   ___ _ __ __ _| |
# | |  _ / _ \ '_ \ / _ \ '__/ _` | |
# | |_| |  __/ | | |  __/ | | (_| | |
#  \____|\___|_| |_|\___|_|  \__,_|_|
#
# 🤖 Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
# General automations, mainly turning on and off lights
#

- alias: Everything off - goodnight
  description: "Go to bed switch, turn off all we don't need during the night. Lights, music, tv, etc"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: switch_round
      event: 1004
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.enable_automatic_lights
  - service: media_player.media_pause
    data:
      entity_id:
        - media_player.kitchen
        - media_player.office
        - media_player.living_room
  - service: light.turn_off
    data:
      entity_id:
        - light.zwave_light_corner_level
        - light.zwave_light_couch_level
  - delay: '1'
  - service: light.turn_off
    data:
      entity_id:
        - light.eetkamer
        - light.kantoor
        - light.ledstrip_office
        - light.keuken
        - light.woonkamer

- alias: Turn on lights when dark - away
  description: "Switch standard lights on when it's after 2 PM and light level too low"
  id: groundfloor_lights_on_when_dark_away
  trigger:
    - platform: numeric_state
      entity_id: sensor.lightlevel_living
      below: 100
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.zwave_light_couch_level
        state: 'off'
      - condition: time
        after: '14:00:00'
        before: '22:30:00'
      - condition: state
        entity_id: input_boolean.enable_automatic_lights
        state: 'on'
      - condition: state
        entity_id:
          - device_tracker.rob_presence
          - device_tracker.steffi_presence
        state:
          - "not_home"
  action:
    - service: notify.telegram_rob
      data:
        message: "💡 Verlichting automatisch aan - niet thuis"
    - service: light.turn_on
      data:
        entity_id:
        - light.zwave_light_corner_level
        - light.zwave_light_couch_level
    - delay: '1'
    - service: light.turn_on
      data:
        entity_id:
        - light.ledstrip_office
        - light.eetkamer
        brightness_pct: 60

- alias: Turn on lights when dark - home
  description: "Switch standard lights on when it's after 2 PM and light level too low"
  id: groundfloor_lights_on_when_dark_home
  trigger:
    - platform: numeric_state
      entity_id: sensor.lightlevel_living
      below: 70
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.zwave_light_couch_level
        state: 'off'
      - condition: time
        after: '14:00:00'
        before: '22:30:00'
      - condition: state
        entity_id: input_boolean.enable_automatic_lights
        state: 'on'
      - condition: or
        conditions:
          - condition: state
            entity_id:
              - device_tracker.rob_presence
            state:
              - "home"
          - condition: state
            entity_id:
              - device_tracker.steffi_presence
            state:
              - "home"
  action:
    - service: notify.telegram_rob
      data:
        message: "💡 Verlichting automatisch aan - thuis"
    - service: light.turn_on
      data:
        entity_id:
        - light.zwave_light_corner_level
        - light.zwave_light_couch_level
        - light.keuken
    - delay: '1'
    - service: light.turn_on
      data:
        entity_id:
        - light.ledstrip_office
        - light.eetkamer
        - light.woonkamer
        brightness_pct: 50

- alias: Turn off lights - bedtime
  description: "Turn off main lights when we're not home or already went to bed"
  trigger:
    platform: time_pattern
    minutes: "/1"
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.zwave_light_couch_level
      state: 'on'
    - condition: time
      after: "23:03:00"
    - condition: state
      entity_id: binary_sensor.samsungtv_livingroom_status
      state: 'off'
    - condition: state
      entity_id: input_boolean.enable_automatic_lights
      state: 'on'
  action:
    - service: notify.telegram_rob
      data:
        message: "💡 Verlichting automatisch uit"
    - service: light.turn_off
      data:
        entity_id:
        - light.zwave_light_corner_level
        - light.zwave_light_couch_level
    - delay: '1'
    - service: light.turn_off
      data:
        entity_id:
        - light.woonkamer
        - light.keuken
        - light.kantoor
        - light.eetkamer

- alias: Turn on lights when closet door opens
  trigger:
    platform: state
    entity_id: sensor.door_hallcloset_openclose
    from: 'Closed'
    to: 'Open'
  action:
    service: light.turn_on
    entity_id: light.hallcloset
- alias: Turn off lights when closet door closes
  trigger:
    platform: state
    entity_id: sensor.door_hallcloset_openclose
    from: 'Open'
    to: 'Closed'
  action:
    service: light.turn_off
    entity_id: light.hallcloset

- alias: Reset lights automation
  description: "When we have disabled all automatic lighting, we reset this in the early morning to make sure we're back to normal the next day"
  id: reset_lights_automation
  trigger:
    platform: time
    at: "05:00:00"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.enable_automatic_lights
        state: "off"
      - condition: state
        entity_id: input_boolean.enable_automatic_garden_lights
        state: "off"
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.enable_automatic_lights
    - service: homeassistant.turn_on
      entity_id: input_boolean.enable_automatic_garden_lights


## Technical workarounds
# somehow I need to reload after a restart as starting isn't enough
- alias: 'Start HomeKit'
  description: "Workaround to reload the homekit integration once more after zwave is done initialising or home assitant is started"
  trigger:
    - platform: event
      event_type: zwave.network_ready
    - platform: event
      event_type: zwave.network_complete
    - platform: event
      event_type: zwave.network_complete_some_dead
    - platform: homeassistant
      event: start
  action:
    - delay: 00:05
    - service: homekit.reload

- alias: 'Restart SSH Addon'
  description: "Restart the ssh addon after a HA restart, required to get the hassio.addon_stdin to work"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: 00:04
    - service: hassio.addon_restart
      data:
        addon: a0d7b954_ssh
    - delay: 00:01
    - service: hassio.addon_stdin
      data:
        addon: a0d7b954_ssh
        input: bash /config/cast.sh
      