#  _   _            _   _
# | | | | ___  __ _| |_(_)_ __   __ _
# | |_| |/ _ \/ _` | __| | '_ \ / _` |
# |  _  |  __/ (_| | |_| | | | | (_| |
# |_| |_|\___|\__,_|\__|_|_| |_|\__, |
#                               |___/
#
# 🤖 Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
#


## Enable infra red heating on working days of Steffi
- alias: "Heating - Turn on heating workspace Steffi"
  description: "This turns on the infra red heating panel when Steffi has to work and is at home."
  trigger:
    - below: "18"
      entity_id: sensor.climate_sensor_guestroom_temperature
      platform: numeric_state
    - platform: time
      at: "07:00:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.workday_steffi
        state: "on"
      - condition: numeric_state
        entity_id: sensor.climate_sensor_guestroom_temperature
        below: "18"
      - condition: state
        entity_id:
          - device_tracker.steffi_presence
        state:
          - "home"
      - after: "07:00"
        condition: time
      - before: "17:00"
        condition: time
  action:
    - service: switch.turn_on
      entity_id: switch.kasa_infrarood_slaapkamer

- alias: "Heating - Turn off heating workspace Steffi"
  description: "This turns off the infra red heating panel when it's warm enough or work day is over or she left"
  trigger:
    - above: "19"
      entity_id: sensor.climate_sensor_guestroom_temperature
      platform: numeric_state
    - platform: time
      at: "16:00:00"
    - platform: state
      entity_id: device_tracker.steffi_presence
      to: "not_home"
      for:
        minutes: 60
  action:
    - service: switch.turn_off
      entity_id: switch.kasa_infrarood_slaapkamer