#  __  __       _ _ _               
# |  \/  | __ _(_) | |__   _____  __
# | |\/| |/ _` | | | '_ \ / _ \ \/ /
# | |  | | (_| | | | |_) | (_) >  < 
# |_|  |_|\__,_|_|_|_.__/ \___/_/\_\
#
# 🤖 Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
# TODO activate / change
# add a led on mailbox to show when mail is available
# based on https://medium.com/@hans.oischinger/make-a-dumb-mailbox-smart-9b7cca648478
#

- alias: Alert when mail in the mailbox
  id: mailbox_notification
  description: "See if there's a vibration in the mailbox, identifying new mail"
  trigger:
    - entity_id: binary_sensor.mailbox_vibration_sensor
      platform: state
      to: "vibration"
  condition: # Trying to prevent more than a single trigger every 20 seconds
    - condition: template
      value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.mailbox_notification.attributes.last_triggered) | int > 20 }}'
    - condition: template
      value_template: '{{ states.automation.mailbox_notification.attributes.last_triggered != none }}'
  action:
    - service: notify.telegram
      data:
        message: "✉ Er is post bezorgd."