#  __  __             _ _             _             
# |  \/  | ___  _ __ (_) |_ ___  _ __(_)_ __   __ _ 
# | |\/| |/ _ \| '_ \| | __/ _ \| '__| | '_ \ / _` |
# | |  | | (_) | | | | | || (_) | |  | | | | | (_| |
# |_|  |_|\___/|_| |_|_|\__\___/|_|  |_|_| |_|\__, |
#                                             |___/ 
#
# 🤖 Author: Rob Sonke
# https://github.com/robsonke/hass-config
#

# this does not run automatically
- alias: "System - Let's Encrypt Renewal"
  description: "Restart the lets encrypt addon, this should renew the certificate"
  trigger:
    platform: time
    at: '01:15:00'
  action:
    - service: hassio.addon_restart
      data:
        addon: core_letsencrypt

# check if pi zeros are up and running
# - alias: "System - Monitor Pi Zeros"
#   description: "Check if the Pi Zeros that are used for monitor.sh are up and running, don't be too impatient with these fellows"
#   trigger:
#     platform: state
#     entity_id:
#       - binary_sensor.pi_zero_monitor_one
#       - binary_sensor.pi_zero_monitor_two
#       - binary_sensor.pi_zero_monitor_three
#       - binary_sensor.pi_zero_monitor_four
#     to: "off"
#     for: "00:30:00"
#   action:
#     service: notify.telegram_rob
#     data_template:
#       message: "💻 {{ state_attr(trigger.entity_id, 'friendly_name') }} is al 30 minuten onbereikbaar."

# check if automatic lights aren't disabled by accident
- alias: Check if automatic lights are disabled by accident
  description: "Check every hour if this wasn't done by accident"
  trigger:
    platform: time_pattern
    hours: "/1"
  condition:
    condition: and
    conditions:
      - condition: time
        after: '5:30:00'
        before: '20:30:00'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.enable_automatic_lights
            state: 'off'
          - condition: state
            entity_id: input_boolean.enable_automatic_garden_lights
            state: 'off'
  action:
    service: notify.telegram_rob
    data_template:
      message: "De automatische verlichting is uitgeschakeld, dit is mogelijk onbewust."

- alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      day: '0'
      actions:
      - service: notify.telegram_rob
        data:
          message: 🔋 Low battery warning for {{sensors|replace("_"," ")}}
