#  __  __             _ _             _             
# |  \/  | ___  _ __ (_) |_ ___  _ __(_)_ __   __ _ 
# | |\/| |/ _ \| '_ \| | __/ _ \| '__| | '_ \ / _` |
# | |  | | (_) | | | | | || (_) | |  | | | | | (_| |
# |_|  |_|\___/|_| |_|_|\__\___/|_|  |_|_| |_|\__, |
#                                             |___/ 
#
# 🤖 Author: Rob Sonke
# https://github.com/robsonke/hass-config
#

# this does not run automatically
- alias: "System - Let's Encrypt Renewal"
  description: "Restart the lets encrypt addon, this should renew the certificate"
  trigger:
    platform: time
    at: '01:15:00'
  action:
    - service: hassio.addon_restart
      data:
        addon: core_letsencrypt

# check if pi zeros are up and running
- alias: System - Monitor Pi Zeros
  description: "Check if the Pi Zeros that are used for monitor.sh are up and running, don't be too impatient with these fellows"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.pi_zero_monitor_one
      - binary_sensor.pi_zero_monitor_two
      - binary_sensor.pi_zero_monitor_three
      - binary_sensor.pi_zero_monitor_four
    to: "off"
    for: "00:30:00"
  action:
    service: notify.telegram_rob
    data_template:
      message: "💻 {{ state_attr(trigger.entity_id, 'friendly_name') }} is al 30 minuten onbereikbaar."
