#  ____                                    
# |  _ \ _ __ ___  ___  ___ _ __   ___ ___ 
# | |_) | '__/ _ \/ __|/ _ \ '_ \ / __/ _ \
# |  __/| | |  __/\__ \  __/ | | | (_|  __/
# |_|   |_|  \___||___/\___|_| |_|\___\___|
#
# 🤖 Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
# Automations that help deciding if we're home or not
#

## get bmw x1 location manually
# TODO downside is that this eats the car's battery
# - alias: 'Track BMW X1 Location'
#   trigger:
#     platform: time_pattern
#     # You can also match on interval. This will match every 5 minutes
#     minutes: "/5"
#   action:
#     - service: bmw_connected_drive.find_vehicle
#       data:
#         vin: !secret bmw_connected_drive_vin


# Somebody is AWAY/HOME now
# TEST
- alias: "Test - Presence detection"
  description: Send a Telegram message in case the presence of a person changes
  trigger:
    platform: state
    for:
      seconds: 15
    entity_id:
      - device_tracker.rob_presence
      - device_tracker.steffi_presence
  condition:
    # do not trigger at hass startup
    - condition: numeric_state
      entity_id: sensor.ha_uptime
      above: 3
    - condition: template
      value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
    service: notify.telegram
    data_template:
      message: "🏠 Status van {{ state_attr(trigger.entity_id, 'friendly_name') }} gewijzigd naar {{ trigger.to_state.state }}"

# Shout through speakers that somebody is arriving when the other one is home
- alias: Presence - Inform that one of us comes home
  description: "Shout through speakers that somebody is arriving when the other one is home"
  trigger:
    platform: state
    for:
      seconds: 15
    entity_id:
      - device_tracker.rob_presence
      - device_tracker.steffi_presence
    to: "just_arrived"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: person.rob
        state: "home"
      - condition: state
        entity_id: person.steffi
        state: "home"
  action:
    - service: tts.google_translate_say
      entity_id: media_player.keuken_display
      data_template:
        message: "Wakker worden, {{ state_attr(trigger.entity_id, 'friendly_name') }} komt er aan!"
    - delay: '2'
    - service: tts.google_translate_say
      entity_id: media_player.office_googlehome
      data_template:
        message: "Wakker worden, {{ state_attr(trigger.entity_id, 'friendly_name') }} komt er aan!"
    - delay: '5'
    - service: automation.trigger
      data:
        entity_id: automation.cast_ha_to_nest_display
        skip_condition: false


# Turning monitor.sh sensors into device trackers, entity names are device_tracker.rob_ble and device_tracker.steffi_ble
# - alias: Rob Occupancy On
#   description: Turning monitor.sh sensors into device trackers - Rob home
#   trigger:
#     - platform: numeric_state
#       entity_id: sensor.home_occupancy_confidence_rob
#       above: 10
#   action:
#     - service: device_tracker.see
#       data:
#         dev_id: ble_rob
#         location_name: home
#         source_type: bluetooth
# - alias: Rob Occupancy Off
#   description: Turning monitor.sh sensors into device trackers - Rob not home
#   trigger:
#     - platform: numeric_state
#       entity_id: sensor.home_occupancy_confidence_rob
#       below: 10
#   action:
#     - service: device_tracker.see
#       data:
#         dev_id: ble_rob
#         location_name: not_home
#         source_type: bluetooth

# - alias: Steffi Occupancy On
#   description: Turning monitor.sh sensors into device trackers - Steffi home
#   trigger:
#     - platform: numeric_state
#       entity_id: sensor.home_occupancy_confidence_steffi
#       above: 10
#   action:
#     - service: device_tracker.see
#       data:
#         dev_id: ble_steffi
#         location_name: home
#         source_type: bluetooth
# - alias: Steffi Occupancy Off
#   description: Turning monitor.sh sensors into device trackers - Steffi not home
#   trigger:
#     - platform: numeric_state
#       entity_id: sensor.home_occupancy_confidence_steffi
#       below: 10
#   action:
#     - service: device_tracker.see
#       data:
#         dev_id: ble_steffi
#         location_name: not_home
#         source_type: bluetooth

# Turn homekit detection into devicetrackers
- alias: Homekit to device trackers - Rob home
  description: Turn homekit detection into device trackers
  trigger:
  - entity_id: input_boolean.rob_homekit_present
    platform: state
  condition:
    - condition: state
      entity_id: input_boolean.rob_homekit_present
      state: 'on'
  action:
    - service: device_tracker.see
      data:
        dev_id: homekit_rob_homekit_present
        location_name: home
        source_type: gps
- alias: Homekit to device trackers - Rob not home
  description: Turn homekit detection into device trackers
  trigger:
  - entity_id: input_boolean.rob_homekit_present
    platform: state
  condition:
    - condition: state
      entity_id: input_boolean.rob_homekit_present
      state: 'off'
  action:
    - service: device_tracker.see
      data:
        dev_id: homekit_rob_homekit_present
        location_name: not_home
        source_type: gps

- alias: Homekit to device trackers - Steffi home
  trigger:
  - entity_id: input_boolean.steffi_homekit_present
    platform: state
  condition:
    - condition: state
      entity_id: input_boolean.steffi_homekit_present
      state: 'on'
  action:
    - service: device_tracker.see
      data:
        dev_id: homekit_steffi_homekit_present
        location_name: home
        source_type: gps
- alias: Homekit to device trackers - Steffi not home
  trigger:
  - entity_id: input_boolean.steffi_homekit_present
    platform: state
  condition:
    - condition: state
      entity_id: input_boolean.steffi_homekit_present
      state: 'off'
  action:
    - service: device_tracker.see
      data:
        dev_id: homekit_steffi_homekit_present
        location_name: not_home
        source_type: gps

# Re-initialise homekit device trackers after a restart of home assistant, required since they sometimes switch to not_home
- alias: Re-initialise homekit device trackers - Rob home
  description: Re-initialise homekit device trackers after a restart of home assistant, required since they sometimes switch to not_home
  trigger:
    platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: input_boolean.rob_homekit_present
      state: 'on'
  action:
    - service: device_tracker.see
      data:
        dev_id: homekit_rob_homekit_present
        location_name: home
        source_type: gps
- alias: Re-initialise homekit device trackers - Rob not home
  description: Re-initialise homekit device trackers after a restart of home assistant, required since they sometimes switch to not_home
  trigger:
    platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: input_boolean.rob_homekit_present
      state: 'off'
  action:
    - service: device_tracker.see
      data:
        dev_id: homekit_rob_homekit_present
        location_name: not_home
        source_type: gps

- alias: Re-initialise homekit device trackers - Steffi home
  trigger:
    platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: input_boolean.steffi_homekit_present
      state: 'on'
  action:
    - service: device_tracker.see
      data:
        dev_id: homekit_steffi_homekit_present
        location_name: home
        source_type: gps
- alias: Re-initialise homekit device trackers - Steffi not home
  trigger:
    platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: input_boolean.steffi_homekit_present
      state: 'off'
  action:
    - service: device_tracker.see
      data:
        dev_id: homekit_steffi_homekit_present
        location_name: not_home
        source_type: gps

- alias: Notify of events in Frigate
  trigger:
    platform: mqtt
    topic: frigate/events
  action:
    - service: notify.telegram
      data_template:
        message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
        data:
          photo:
            - url: 'http://ccab4aaf-frigate:5000/api/events/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg'
              caption: 'A {{trigger.payload_json["after"]["label"]}} was detected on {{ trigger.payload_json["after"]["camera"] }} camera'

# Restart monitor nodes when hass restarts
- alias: Restart monitor.sh at Hass startup
  description: Restart monitor nodes when hass restarts
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic : monitor/raspberrypi-zero-1/KNOWN DEVICE STATES
        payload: ""
    - service: mqtt.publish
      data:
        topic : monitor/raspberrypi-zero-2/KNOWN DEVICE STATES
        payload: ""
    - service: mqtt.publish
      data:
        topic : monitor/raspberrypi-zero-3/KNOWN DEVICE STATES
        payload: ""
