#  ____          _ _       _               
# / ___|_      _(_) |_ ___| |__   ___  ___ 
# \___ \ \ /\ / / | __/ __| '_ \ / _ \/ __|
#  ___) \ V  V /| | || (__| | | |  __/\__ \
# |____/ \_/\_/ |_|\__\___|_| |_|\___||___/
#
# 🤖 Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
# Philips Hue switches
#

- alias: 'Toggle kitchen light from dimmer'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: dimmer_switch_kitchen
        event: 1002
  action:
    service: light.toggle
    entity_id: light.kitchen
- alias: 'Turn off kitchen light from dimmer'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch_kitchen
      event: 4002
  action:
    service: light.turn_off
    entity_id: light.kitchen
- alias: 'Increase brightness of kitchen light from dimmer'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch_kitchen
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kitchen
        brightness: >
          {% set bri = state_attr('light.kitchen', 'brightness') | int %}
          {{ [bri+30, 249] | min }}
- alias: 'Decrease brightness of kitchen light from dimmer'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch_kitchen
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kitchen
        brightness: >
          {% set bri = state_attr('light.kitchen', 'brightness') | int %}
          {{ [bri-30, 0] | max }}

# office light switch
- alias: 'Toggle office light from dimmer'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch_office
      event: 1002
  action:
    service: light.toggle
    entity_id: light.office
- alias: 'Turn off office light from dimmer'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch_office
      event: 4002
  action:
    service: light.turn_off
    entity_id: light.office
- alias: 'Increase brightness of office light from dimmer'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch_office
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.office
        brightness: >
          {% set bri = state_attr('light.office', 'brightness') | int %}
          {{ [bri+30, 249] | min }}
- alias: 'Decrease brightness of office light from dimmer'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch_office
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.office
        brightness: >
          {% set bri = state_attr('light.office', 'brightness') | int %}
          {{ [bri-30, 0] | max }}
