# __     __                               
# \ \   / /_ _  ___ _   _ _   _ _ __ ___  
#  \ \ / / _` |/ __| | | | | | | '_ ` _ \ 
#   \ V / (_| | (__| |_| | |_| | | | | | |
#    \_/ \__,_|\___|\__,_|\__,_|_| |_| |_|
#
# 🤖 Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
# Automations for Sjorsje, the Vacuum Cleaner Robot
#

- alias: Sjorsje Bin Full
  trigger:
    - entity_id: binary_sensor.sjorsje_bin_full
      platform: state
      to: 'true'
  action:
    service: notify.telegram
    data_template:
      message: "🧹 Sjorsje's opvangbak zit bol"

- alias: Sjorsje Battery Empty
  trigger:
    - entity_id: sensor.sjorsje_battery_level
      platform: numeric_state
      below: 20
  action:
    service: notify.telegram
    data_template:
      message: "🔋 Sjorsje's accu raakt leeg"


