action_command:
  name: "Action command"
  description: "Execute action command on charger"
  fields:
    device_id:
      name: Target device
      description: "Select the charger to control"
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"
    action_command:
      name: "Action command"
      description: "Select the command to execute"
      required: true
      example: "resume"
      selector:
        select:
          options:
            - label: Start
              value: "start"
            - label: Stop
              value: "stop"
            - label: Toggle
              value: "toggle"
            - label: Pause
              value: "pause"
            - label: Resume
              value: "resume"
            - label: Reboot
              value: "reboot"
            - label: Update firmware
              value: "update_firmware"
            - label: Override schedule
              value: "override_schedule"
            - label: Delete basic charge plan
              value: "delete_basic_charge_plan"

set_basic_charge_plan:
  name: "Set basic charge plan"
  description: "Set basic charge plan"
  fields:
    device_id:
      name: Target device
      description: "Select the charger to control"
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"
    start_datetime:
      name: "Start datetime"
      description: "Plan start time"
      required: true
      example: "2020-07-28T19:51"
      selector:
        datetime:
    stop_datetime:
      name: "Stop datetime"
      description: "Plan stop time"
      required: false
      example: "2020-07-28T19:51"
      selector:
        datetime:
    repeat:
      name: "Repeat plan"
      description: "Repeat plan"
      required: true
      example: true
      selector:
        boolean:

smart_charging:
  name: "Smart charging"
  description: "Enable/disable smart charging"
  fields:
    device_id:
      name: Target device
      description: "Select the charger that should be controlled."
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"
    enable:
      name: "Enable"
      description: "Enable smart charging"
      required: True
      example: True
      selector:
        boolean:

set_circuit_max_limit:
  name: "Set circuit max limit"
  description: "Set circuit max limit. Caution! Should not be used by automation (may wear out flash memory if set too frequently)."
  fields:
    device_id:
      name: Target device
      description: "Select one of the chargers in the circuit that should be controlled."
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"
    currentP1:
      name: "Current Phase 1"
      required: true
      description: "Max charging current"
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider
    currentP2:
      name: "Current Phase 2"
      required: false
      description: "Max charging current. If disabled, the value of Current Phase 1 will be used"
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider
    currentP3:
      name: "Current Phase 3"
      required: false
      description: "Max charging current. If disabled, the value of Current Phase 1 will be used"
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider

set_circuit_offline_limit:
  name: "Set circuit offline limit"
  description: "Set circuit offline limit used if charger is offline (fallback). Caution! Should not be used by automation (may wear out flash memory if set too frequently)."
  fields:
    device_id:
      name: Target device
      description: "Select one of the chargers in the circuit that should be controlled."
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"
    currentP1:
      name: "Current Phase 1"
      required: true
      description: "Max charging current"
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider
    currentP2:
      name: "Current Phase 2"
      required: false
      description: "Max charging current. If disabled, the value of Current Phase 1 will be used"
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider
    currentP3:
      name: "Current Phase 3"
      required: false
      description: "Max charging current. If disabled, the value of Current Phase 1 will be used"
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider

set_charger_dynamic_limit:
  name: "Set charger dynamic limit"
  description: "Set charger dynamic limit"
  fields:
    device_id:
      name: Target device
      description: "Select one of the chargers in the circuit that should be controlled."
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"
    current:
      name: "Current"
      required: true
      description: "Max charging current"
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider

set_circuit_dynamic_limit:
  name: "Set circuit dynamic limit"
  description: "Set circuit dynamic limit (shared betwwen chargers on that circuit). This service can be used in automations."
  fields:
    device_id:
      name: Target device
      description: "Select one of the chargers in the circuit that should be controlled."
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"
    currentP1:
      name: "Current Phase 1"
      required: true
      description: "Max charging current"
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider
    currentP2:
      name: "Current Phase 2"
      required: false
      description: "Max charging current. If disabled, the value of Current Phase 1 will be used"
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider
    currentP3:
      name: "Current Phase 3"
      required: false
      description: "Max charging current. If disabled, the value of Current Phase 1 will be used"
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider
    time_to_live:
      name: "Time to live"
      required: false
      description: "Set time in minutes for the command to live. 0 = indefinitely."
      example: 0
      default: 0
      selector:
        number:
          min: 0
          max: 1080
          step: 1
          unit_of_measurement: "min"
          mode: box

set_charger_max_limit:
  name: "Set charger max limit"
  description: "Set charger max limit. Caution! Should not be used by automation (may wear out flash memory if set too frequently)."
  fields:
    device_id:
      name: Target device
      description: "Select one of the chargers in the circuit that should be controlled."
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"
    current:
      name: "Current"
      required: true
      description: "Max charging current"
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider

set_charging_cost:
  name: "Set charging cost"
  description: "Set charging cost per kWh for charger site"
  fields:
    device_id:
      name: Target device
      description: "Select one of the chargers in the circuit that should be controlled."
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"
    cost_per_kwh:
      name: "Cost per kWh"
      description: "Cost per kWh"
      example: 0.3
      default: 0
      required: true
      selector:
        number:
          mode: box
    vat:
      name: VAT
      description: "VAT"
      required: False
      example: 25.0
      default: 0
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: box
    currency_id:
      name: "Currency"
      description: "Currency code"
      example: "EUR"
      required: false
      selector:
        text:
          type: text

set_charger_access:
  name: "Set charger access"
  description: "Set access level on the charger"
  fields:
    device_id:
      name: Target device
      description: "Select the charger to control"
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          model: "Charging Robot"
    access_level:
      name: "Access level"
      description: "Select one of the levels"
      example: 1
      required: true
      selector:
        select:
          options:
            - label: Open for all
              value: "1"
            - label: Require Easee account
              value: "2"
            - label: Whitelist
              value: "3"
