action_command:
  fields:
    device_id:
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          # This is needed to exclude Equalizers from the target list"
          entity:
            domain: "switch"
    action_command:
      required: true
      example: "resume"
      selector:
        select:
          translation_key: action_command
          options:
            - start
            - stop
            - toggle
            - pause
            - resume
            - update_firmware
            - override_schedule
            - delete_basic_charge_plan
            - enable_basic_charge_plan
            - disable_basic_charge_plan
            - delete_weekly_charge_plan
            - enable_weekly_charge_plan
            - disable_weekly_charge_plan

set_basic_charge_plan:
  fields:
    device_id:
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          entity:
            domain: "switch"
    start_datetime:
      required: true
      example: "2020-07-28T19:51"
      selector:
        datetime:
    stop_datetime:
      required: false
      example: "2020-07-28T19:51"
      selector:
        datetime:
    repeat:
      required: true
      example: true
      selector:
        boolean:
    current:
      required: false
      example: 16
      default: 32
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider

set_weekly_charge_plan:
  fields:
    device_id:
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          entity:
            domain: "switch"
    day:
      required: true
      example: monday
      selector:
        select:
          translation_key: weekday
          options:
            - monday
            - tuesday
            - wednesday
            - thursday
            - friday
            - saturday
            - sunday
    start_time:
      required: true
      example: "19:51"
      selector:
        time:
    stop_time:
      required: true
      example: "20:51"
      selector:
        time:
    current:
      required: false
      example: 16
      default: 32
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider

smart_charging:
  fields:
    device_id:
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          entity:
            domain: "switch"
    enable:
      required: True
      example: True
      selector:
        boolean:

set_circuit_max_limit:
  fields:
    device_id:
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          entity:
            domain: "switch"
    current_p1:
      required: true
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider
    current_p2:
      required: false
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider
    current_p3:
      required: false
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider

set_circuit_offline_limit:
  fields:
    device_id:
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          entity:
            domain: "switch"
    current_p1:
      # Todo: Reinstate after deprecation period
      # required: true
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider
    current_p2:
      required: false
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider
    current_p3:
      required: false
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider

set_charger_dynamic_limit:
  fields:
    device_id:
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          entity:
            domain: "switch"
    current:
      required: true
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider

set_circuit_dynamic_limit:
  fields:
    device_id:
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          entity:
            domain: "switch"
    current_p1:
      required: true
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider
    current_p2:
      required: false
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider
    current_p3:
      required: false
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider
    time_to_live:
      required: false
      example: 0
      default: 0
      selector:
        number:
          min: 0
          max: 1080
          step: 1
          unit_of_measurement: "min"
          mode: box

set_charger_max_limit:
  fields:
    device_id:
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          entity:
            domain: "switch"
    current:
      required: true
      example: 16
      default: 16
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider

set_charging_cost:
  fields:
    device_id:
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          entity:
            domain: "switch"
    cost_per_kwh:
      example: 0.3
      default: 0
      required: true
      selector:
        number:
          mode: box
    vat:
      required: False
      example: 25.0
      default: 0
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: box
    currency_id:
      example: "EUR"
      required: false
      selector:
        text:
          type: text

set_charger_access:
  fields:
    device_id:
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          entity:
            domain: "switch"
    access_level:
      example: 1
      required: true
      selector:
        select:
          translation_key: access_level
          options:
            - open_for_all
            - require_easee_account
            - whitelist

set_charger_phase_mode:
  fields:
    device_id:
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          entity:
            domain: "switch"
    phase_mode:
      example: auto_phase
      required: true
      selector:
        select:
          translation_key: phase_mode
          options:
            - 1_phase
            - auto_phase
            - 3_phase

set_surplus_charging:
  fields:
    device_id:
      required: true
      example: "b40f1f45d28b0891fe8d"
      selector:
        device:
          integration: "easee"
          model: "Equalizer"
    enable:
      required: True
      example: True
      selector:
        boolean:
    current:
      required: true
      example: 16
      default: 0
      selector:
        number:
          min: 0
          max: 40
          step: 1
          unit_of_measurement: "A"
          mode: slider
