#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
- platform: manual
  name: Alarm
  code: !secret alarm_code
  # Don't require the code to arm the alarm
  code_arm_required: false
  # Arm again after triggering
  disarm_after_trigger: false
  # Delay from arming and becoming armed, eg. to leave the house.
  arming_time: 120
  # Allow time to disarm the alarm before it triggers, eg. when arriving home
  delay_time: 120
  # Amount of time the alarm is triggered for
  trigger_time: 600
  disarmed:
    # Ensure the alarm can never be directly triggered when disarmed
    trigger_time: 0