#  ____  _                          ____                                
# | __ )(_)_ __   __ _ _ __ _   _  / ___|  ___ _ __  ___  ___  _ __ ___ 
# |  _ \| | '_ \ / _` | '__| | | | \___ \ / _ \ '_ \/ __|/ _ \| '__/ __|
# | |_) | | | | | (_| | |  | |_| |  ___) |  __/ | | \__ \ (_) | |  \__ \
# |____/|_|_| |_|\__,_|_|   \__, | |____/ \___|_| |_|___/\___/|_|  |___/
#                           |___/                                       
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
- platform: ping
  host: !secret tvliving_host
  name: samsungtv_livingroom_status

- platform: ping
  # office
  name: pi_zero_monitor_one
  host: !secret pi_zero_monitor_one_host
  scan_interval: 30
- platform: ping
  # bedroom
  name: pi_zero_monitor_two
  host: !secret pi_zero_monitor_two_host
  scan_interval: 30
- platform: ping
  # living room
  name: pi_zero_monitor_three
  host: !secret pi_zero_monitor_three_host
  scan_interval: 30
- platform: ping
  # spare
  name: pi_zero_monitor_four
  host: !secret pi_zero_monitor_four_host
  scan_interval: 30

# Frigate
- name: Gardencam Person Frigate
  platform: mqtt
  off_delay: 0
  state_topic: "frigate/gardencam/person"
  device_class: motion
  availability_topic: "frigate/available"
- name: Babycam Person Frigate
  platform: mqtt
  off_delay: 0
  state_topic: "frigate/babycam/person"
  device_class: motion
  availability_topic: "frigate/available"
