#   ____                                   
#  / ___|__ _ _ __ ___   ___ _ __ __ _ ___ 
# | |   / _` | '_ ` _ \ / _ \ '__/ _` / __|
# | |__| (_| | | | | | |  __/ | | (_| \__ \
#  \____\__,_|_| |_| |_|\___|_|  \__,_|___/
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
- platform: foscam
  ip: !secret babycam_ip
  port: 88
  rtsp_port: 88
  username: !secret babycam_username
  password: !secret babycam_password
  name: Babycam
- platform: foscam
  ip: !secret gardencam_ip
  port: 88
  rtsp_port: 88
  username: !secret babycam_username
  password: !secret babycam_password
  name: Gardencam
- platform: generic
  name: Weer
  still_image_url: "https://api.buienradar.nl/image/1.0/RadarMapNL?w=480&h=480"
  content_type: "image/gif"

  # Frigate
- name: Gardencam Last Person Frigate
  platform: mqtt
  topic: frigate/gardencam/person/snapshot

- name: Babycam Last Person Frigate
  platform: mqtt
  topic: frigate/babycam/person/snapshot