#  _     _       _     _       
# | |   (_) __ _| |__ | |_ ___ 
# | |   | |/ _` | '_ \| __/ __|
# | |___| | (_| | | | | |_\__ \
# |_____|_|\__, |_| |_|\__|___/
#          |___/               
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#


- platform: casambi
  email: !secret casambi_email
  api_key: !secret casambi_api_key
  network_password : !secret casambi_network_password
  user_password : !secret casambi_user_password
  network_timeout: 30

- platform: group
  name: Woonkamer
  entities:
    - light.woonkamer_achter
    - light.woonkamer_voor
- platform: group
  name: Overloop
  entities:
    - light.overloop_1
    - light.overloop_2
- platform: group
  name: Keuken
  entities:
    - light.keuken_kook
    - light.keuken_nis
