#  _               _
# | |    ___   ___| | _____
# | |   / _ \ / __| |/ / __|
# | |__| (_) | (__|   <\__ \
# |_____\___/ \___|_|\_\___/
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#

- platform: nuki
  host: !secret nuki_bridge_host
  token: !secret nuki_api_key