#  ____                                
# / ___|  ___ _ __  ___  ___  _ __ ___ 
# \___ \ / _ \ '_ \/ __|/ _ \| '__/ __|
#  ___) |  __/ | | \__ \ (_) | |  \__ \
# |____/ \___|_| |_|___/\___/|_|  |___/
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#

- platform: version

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'

- platform: moon
- platform: uptime
- platform: dnsip

# tracks changes in the lovelace file
- platform: filesize
  file_paths:
    - /config/.storage/lovelace

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot

- platform: unifigateway
  host: !secret router_ip
  port: 443
  version: 'UDMP-unifiOS'
  username: !secret unifi_username
  password: !secret unifi_password
  verify_ssl: false
  monitored_conditions:
    - www
    - lan
    - wan
    - wlan
    - alerts
    - firmware
