#  _____    _                                
# |_   _|__| | ___  __ _ _ __ __ _ _ __ ___  
#   | |/ _ \ |/ _ \/ _` | '__/ _` | '_ ` _ \ 
#   | |  __/ |  __/ (_| | | | (_| | | | | | |
#   |_|\___|_|\___|\__, |_|  \__,_|_| |_| |_|
#                  |___/                     
#
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
- platform: polling
  api_key: !secret telegram_api_key
  parse_mode: html
  allowed_chat_ids:
    - !secret telegram_chat_id