#  _____ _____ ____  
# |_   _|_   _/ ___| 
#   | |   | | \___ \ 
#   | |   | |  ___) |
#   |_|   |_| |____/ 
#
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
- platform: google_translate
  language: 'nl'