# __        __         _   _               
# \ \      / /__  __ _| |_| |__   ___ _ __ 
#  \ \ /\ / / _ \/ _` | __| '_ \ / _ \ '__|
#   \ V  V /  __/ (_| | |_| | | |  __/ |   
#    \_/\_/ \___|\__,_|\__|_| |_|\___|_|   
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
- platform: buienradar
  name: !secret weather_city
  forecast: true