
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${ip}
    gateway: 192.168.0.1
    subnet: 255.255.255.0

captive_portal:

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret wifi_password

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time