substitutions:
  devicename: m5stack-pool
  #ip: !secret shellyplug2_ip
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  api_key: !secret api_key

esphome:
  name: ${devicename}
  friendly_name: ${devicename}

  includes:
    - custom_components/axp192/axp192.h
    - custom_components/st7735/st7735.h

esp32:
  board: m5stack-core-esp32
  framework:
    type: arduino

  

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: ${api_key}

ota:
  password: ${password}

wifi:
  ssid: ${ssid}
  password: ${password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Stack-Pool Fallback Hotspot"
    password: "Tn0FWyHmrtpj"

captive_portal:

web_server:
  port: 80


spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO38
  
i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: True

sensor:
  - platform: axp192
    #model: M5CORE2
    address: 0x34
    i2c_id: bus_a
    update_interval: 30s
    battery_level:
      name: "${devicename} Battery Level"
      id: "m5stack_pool_batterylevel"

  - platform: wifi_signal
    name: ${devicename} WiFi Signal
    id: wifi_dbm
  - platform: uptime
    name: ${devicename} Uptime

# display:
#   - platform: ili9341
#     model: M5STACK
#     cs_pin: 5
#     dc_pin: 15
#     lambda: |-
#       it.line(20, 20, 200, 200);