substitutions:
  ip: !secret pool_lights_ip
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  api_key: !secret api_key_pool_lights

esphome:
  name: "pool-lights"
  friendly_name: pool-lights

  

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: ${api_key}

ota:

wifi:
  ssid: ${ssid}
  password: ${password}
  manual_ip:
    static_ip: ${ip}
    gateway: 192.168.0.1
    subnet: 255.255.255.0

captive_portal:

web_server:
  port: 80


# GPIO1 (TX0) and GPIO3 (RX0)
# ESP32 GPIO PIN 16 to TXD PIN 17 to RXD
uart:
  id: mod_bus
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 9600
  stop_bits: 1
  parity: EVEN

modbus:
  id: modbus1
  uart_id: mod_bus

modbus_controller:
  - id: ctrl1
    address: 0x01
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 5s


# sensor:
#   - platform: modbus_controller
#     modbus_controller_id: a8s
#     name: "Voltage"
#     id: modbus_voltage
#     register_type: holding
#     address: 0x64
#     unit_of_measurement: "V"
#     value_type: FP32
#     accuracy_decimals: 2