homeassistant: true
mqtt:
  server: mqtt://192.168.0.40:1883
  user: mqtt_ha
  password: cFXeDaAe99pViUZPa16E
  base_topic: zigbee2mqtt
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_7e834311c712ec11900b23c7bd930c07-if00-port0
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: debug
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  transmit_power: 20
device_options:
  legacy: false
devices:
  '0x00158d00053e7146':
    friendly_name: window_office_openclose
  '0x0017880108b03b76':
    friendly_name: hallcloset_light
  '0x00158d00052da1fb':
    friendly_name: door_hallcloset_openclose
  '0xcc86ecfffee6540d':
    friendly_name: office_light
  '0x7cb03eaa0a006f53':
    friendly_name: ledstrip_office
  '0x04cf8cdf3c775d4c':
    friendly_name: light_sensor_garden
  '0x00158d00053e0096':
    friendly_name: climate_sensor_office
  '0x00158d00053e9699':
    friendly_name: hallwaydoor_openclose
  '0x00158d000705c960':
    friendly_name: toiletdoordownstairs_openclose
  '0x00158d00058a83d1':
    friendly_name: motion_sensor_toiletdownstairs
  '0x0c4314fffe9fa221':
    friendly_name: toilet_downstairs_light
  '0x7cb03eaa00b02d1b':
    friendly_name: ledstrip_tv
  '0xcc86ecfffee97782':
    friendly_name: kitchen_light
  '0xb4e3f9fffe2b9fa1':
    friendly_name: kitchendesk_light
  '0xcc86ecfffee97987':
    friendly_name: livingfront_light
  '0xcc86ecfffee97774':
    friendly_name: livingback_light
  '0x00158d0004aaded4':
    friendly_name: climate_sensor_kitchen
  '0x04cf8cdf3c7b5c1c':
    friendly_name: light_sensor_kitchen
  '0x00158d0004aadf40':
    friendly_name: climate_sensor_living
  '0x04cf8cdf3c773066':
    friendly_name: light_sensor_living
  '0x00158d0004773528':
    friendly_name: frontdoor_openclose
  '0xcc86ecfffee65446':
    friendly_name: kitchencabin_light
  '0x00158d0004a97335':
    friendly_name: windowdoor_ground_1_openclose
  '0x00158d00052da0b1':
    friendly_name: windowdoor_ground_2_openclose
  '0x7cb03eaa0a0063d2':
    friendly_name: ledstrip_book3
  '0x7cb03eaa0a007cb8':
    friendly_name: ledstrip_book2
  '0x7cb03eaa0a007c56':
    friendly_name: ledstrip_book1
  '0xcc86ecfffee979c5':
    friendly_name: dining_light
  '0x00158d0004abcc80':
    friendly_name: windowdoor_ground_3_openclose
  '0x00158d00053e9a61':
    friendly_name: windowdoor_ground_4_openclose
  '0x842e14fffe779d3a':
    friendly_name: range_extender_tradfri_dining
  '0x00158d00070647b2':
    friendly_name: backdoor_openclose
  '0x00158d00058277d6':
    friendly_name: motion_sensor_cats
  '0x00158d0006ffdb3f':
    friendly_name: sheddoor_openclose
  '0x001788010b0791d3':
    friendly_name: garden_lantern_light1
  '0xcc86ecfffee977d3':
    friendly_name: garden_light
  '0x001788010b83a9b7':
    friendly_name: garden_lantern_light2
  '0x001788010b851045':
    friendly_name: garden_lantern_light3
  '0x0017880109c4a18c':
    friendly_name: hue_lily_light_tree_1
  '0x0017880109c0bdaa':
    friendly_name: hue_lily_light_fence_1
  '0x0017880109c46fca':
    friendly_name: hue_lily_light_fence_2
  '0x84fd27fffecdeae9':
    friendly_name: range_extender_tradfri_guest
  '0x00158d00053fdd80':
    friendly_name: window_eva_openclose
  '0x00158d00053e0558':
    friendly_name: window_guestroom_openclose
  '0x00158d00053d6c24':
    friendly_name: window_noaroom_openclose
  '0x00158d00053fdd47':
    friendly_name: window_masterbed_2_openclose
  '0x00158d00052d5574':
    friendly_name: window_masterbed_1_openclose
  '0x00158d00053e0059':
    friendly_name: climate_sensor_masterbedroom
  '0x04cf8cdf3c7b4d13':
    friendly_name: light_sensor_masterbedroom
  '0x00158d00049fb442':
    friendly_name: sheddoor_back_openclose
  '0xb4e3f9fffe2ba069':
    friendly_name: diningtable_light
  '0x0017880109c472f8':
    friendly_name: hue_lily_light_fence_3
  '0x00158d0007103985':
    friendly_name: cabindoor_openclose
    debounce: 1
    homeassistant: {}
    legacy: false
    optimistic: true
  '0x00158d0007ec9128':
    friendly_name: door_terrace_openclose
  '0x8cf681fffe109d41':
    friendly_name: switch_alarm_activity
  '0x00158d0007e66b1b':
    friendly_name: climate_sensor_guestroom
  '0x84b4dbfffe0de05b':
    friendly_name: woodshed_light
  '0x001788010c5ba9c2':
    friendly_name: palm1_light
  '0x001788010bf0fda4':
    friendly_name: palm2_light
  '0x001788010b972c35':
    friendly_name: pool_terrace_light1
  '0x001788010b9ceab7':
    friendly_name: pool_terrace_light2
  '0x001788010b408f59':
    friendly_name: hue_lily_light_tree_2
  '0x001788010cc52e69':
    friendly_name: hue_bathroom_switch
  '0x385b44fffe0f1ea1':
    friendly_name: dimmer_bathroom
  '0x385b44fffe33ff18':
    friendly_name: veranda_light
  '0x001788010d9f4e51':
    friendly_name: hue_guestroom_switch
  '0x385b44fffe385244':
    friendly_name: dimmer_guestroom
  '0x385b44fffe2e14b0':
    friendly_name: dimmer_hall
  '0x001788010d9f4e4f':
    friendly_name: hue_corridor2_switch
  '0x001788010cc568fd':
    friendly_name: hue_eva_switch
  '0x001788010d9f5316':
    friendly_name: hue_noa_switch
  '0x385b44fffe144ecb':
    friendly_name: dimmer_corridor1
  '0x385b44fffe3405ed':
    friendly_name: dimmer_corridor2
  '0x385b44fffe144dde':
    friendly_name: dimmer_eva
  '0x385b44fffe2ce244':
    friendly_name: dimmer_noa
  '0x385b44fffe2e024c':
    friendly_name: dimmer_masterbed
  '0x385b44fffe2cdebc':
    friendly_name: dimmer_mastercloset
  '0x385b44fffe2e0578':
    friendly_name: dimmer_masterbath
  '0x001788010d7cb9f9':
    friendly_name: hue_tap_switch_master
  '0x60a423fffe09143f':
    friendly_name: garden_socket
  '0x001788010cd8154e':
    friendly_name: hue_motion_sensor_corridor1
  '0x001788010cd81cef':
    friendly_name: hue_motion_sensor_shed
  '0x540f57fffefc3267':
    friendly_name: switch_sonoff_shed
    state_action: false
  '0x001788010cd8e833':
    friendly_name: hue_motion_sensor_shower
  '0x385b44fffe1457af':
    friendly_name: toilet_upstairs_light
  '0x00158d0007ec9289':
    friendly_name: toiletdoorupstairs_openclose
    homeassistant: {}
    legacy: false
    optimistic: true
    retain: true
  '0x00158d00075be992':
    friendly_name: socket2_light_couch
  '0x00158d00075b481d':
    friendly_name: socket1_light_corner
  '0x00158d00075affaa':
    friendly_name: socket4_light_spare2
    disabled: false
    homeassistant: {}
    legacy: false
    optimistic: true
  '0x00158d00075b0030':
    friendly_name: socket3_light_spare1
    disabled: false
    homeassistant: {}
    legacy: false
    optimistic: true
  '0x60b647fffe7b8ee2':
    friendly_name: bedroom_sonos_light
  '0xf082c0fffe25c2e7':
    friendly_name: office_light_switch
  '0x001788010cc568f7':
    friendly_name: hue_hall_switch
  '0x001788010e2549c5':
    friendly_name: hue_corridor_switch
  '0x00158d000533c62a':
    friendly_name: climate_sensor_eva
  '0x00158d0007e68332':
    friendly_name: climate_sensor_noa
  '0x00158d0007e7531d':
    friendly_name: motion_sensor_toiletupstairs
  '0x001788010e503a66':
    friendly_name: hue_motion_sensor_hall
availability:
  active:
    timeout: 10
  passive:
    timeout: 720
groups:
  '1':
    friendly_name: dimmer_corridor
    devices:
      - 0x385b44fffe144ecb/1
      - 0x385b44fffe3405ed/1
  '2':
    friendly_name: dimmer_master_closetbath
    devices:
      - 0x385b44fffe2cdebc/1
      - 0x385b44fffe2e0578/1
  '3':
    friendly_name: ledstrip_book
    devices:
      - 0x7cb03eaa0a007cb8/3
      - 0x7cb03eaa0a0063d2/3
      - 0x7cb03eaa0a007c56/3
permit_join: true
blocklist: []
ota:
  ikea_ota_use_test_url: true
