homeassistant: true
advanced:
  network_key:
    - 52
    - 27
    - 7
    - 134
    - 159
    - 122
    - 75
    - 50
    - 182
    - 49
    - 221
    - 145
    - 17
    - 242
    - 139
    - 231
  pan_id: 2513
  ext_pan_id:
    - 157
    - 26
    - 185
    - 39
    - 241
    - 249
    - 193
    - 133
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  channel: 20
mqtt:
  server: mqtt://192.168.0.40:1883
  user: mqtt_ha
  password: cFXeDaAe99pViUZPa16E
  keepalive: 60
  reject_unauthorized: true
  version: 4
  base_topic: zigbee2mqtt-sky
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2128703-if00
  adapter: deconz
  baudrate: 115200
frontend:
  port: 8099
device_options:
  legacy: false
devices: {}
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
