#   ____          _                  _           _   _             
#  / ___|   _ ___| |_ ___  _ __ ___ (_)___  __ _| |_(_) ___  _ __  
# | |  | | | / __| __/ _ \| '_ ` _ \| / __|/ _` | __| |/ _ \| '_ \ 
# | |__| |_| \__ \ || (_) | | | | | | \__ \ (_| | |_| | (_) | | | |
#  \____\__,_|___/\__\___/|_| |_| |_|_|___/\__,_|\__|_|\___/|_| |_|
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#

homeassistant:
  customize_domain:
    light:
      assumed_state: false
  customize:
    person.rob:
      entity_picture: "/local/images/rob_icon-mirror.png"
    person.steffi:
      entity_picture: "/local/images/steffi_icon.png"
    zone.home:
      entity_picture: "/local/images/huis_langeweide_icon.png"
    device_tracker.rob_presence:
      friendly_name: Combined Presence Rob
    device_tracker.steffi_presence:
      friendly_name: Combined Presence Steffi

    light.boekenkast:
      icon: mdi:led-strip-variant
    media_player.living_room:
      friendly_name: Speakers Woonkamer
    media_player.tv_room:
      friendly_name: Speakers TV
    media_player.eetkamer:
      friendly_name: Speakers Eetkamer
    media_player.office:
      friendly_name: Speakers Kantoor
    light.zwave_light_couch_level:
      friendly_name: Lamp bank
    light.hallcloset:
      icon: mdi:globe-light
      friendly_name: Lamp gangkast

    switch.kasa_infrarood_slaapkamer:
      icon: mdi:radiator
    binary_sensor.backdoor_openclose_sensor:
      friendly_name: Achterdeur
      device_class: door
    binary_sensor.frontdoor_openclose_sensor:
      friendly_name: Voordeur
      device_class: door
    binary_sensor.sheddoor_openclose_sensor:
      friendly_name: Schuurdeur
      device_class: door
    binary_sensor.sheddoor_back_openclose_sensor:
      friendly_name: Schuurdeur achter
      device_class: door
    binary_sensor.cabindoor_openclose_contact:
      friendly_name: Blokhutdeur
      device_class: door
    binary_sensor.windowdoor_ground_1_openclose_sensor:
      friendly_name: Kanteldeur beneden 1
      device_class: door
    binary_sensor.windowdoor_ground_2_openclose_sensor:
      friendly_name: Kanteldeur beneden 2
      device_class: door
    binary_sensor.windowdoor_ground_3_openclose_sensor:
      friendly_name: Kanteldeur beneden 3
      device_class: door
    binary_sensor.windowdoor_ground_4_openclose_sensor:
      friendly_name: Kanteldeur beneden 4
      device_class: door
    binary_sensor.window_office_openclose_sensor:
      friendly_name: Raam kantoor
      device_class: window
    binary_sensor.door_hallcloset_openclose_sensor:
      friendly_name: Deur gangkast
      device_class: door
    binary_sensor.hallwaydoor_openclose_sensor:
      friendly_name: Deur gang
      device_class: door
    binary_sensor.toiletdoordownstairs_openclose:
      friendly_name: Deur wc beneden
      device_class: door
    binary_sensor.window_atticroom_openclose_sensor:
      friendly_name: Raam zolderkamer
      device_class: window
    binary_sensor.window_guestroom_openclose_sensor:
      friendly_name: Raam logeerkamer
      device_class: window
    binary_sensor.window_evaroom_openclose_sensor:
      friendly_name: Raam Eva
      device_class: window
    binary_sensor.window_masterbed_1_openclose_sensor:
      friendly_name: Raam master bedroom 1
      device_class: window
    binary_sensor.window_masterbed_2_openclose_sensor:
      friendly_name: Raam master bedroom 2
      device_class: window

    binary_sensor.mailbox_vibration_sensor:
      friendly_name: Brievenbus
      icon: mdi:mailbox

    sensor.switch_1_battery_level:
      friendly_name: Schakelaar 1 batterij
    sensor.dimmer_switch_kitchen_battery_level:
      friendly_name: Dimmer keuken batterij
    sensor.dimmer_switch_office_battery_level:
      friendly_name: Dimmer kantoor batterij

    sensor.lightlevel_office:
      friendly_name: Licht sensor kantoor
    sensor.lightlevel_office_battery_level:
      friendly_name: Licht sensor kantoor batterij
    sensor.lightlevel_living:
      friendly_name: Licht sensor woonkamer
    sensor.lightlevel_living_battery_level:
      friendly_name: Licht sensor woonkamer batterij

    sensor.climate_sensor_office_temperature:
      friendly_name: Temperatuur sensor kantoor
    sensor.climate_sensor_office_humidity:
      friendly_name: Luchtvochtigheid sensor kantoor
    sensor.climate_sensor_office_pressure:
      friendly_name: Luchtdruk sensor kantoor
    sensor.climate_sensor_office_battery_level:
      friendly_name: Klimaat sensor kantoor batterij

    sensor.altherma_energy_usage:
      device_class: energy
      state_class: total_increasing
      unit_of_measurement: kWh
    sensor.altherma_energy_usage_secundary:
      device_class: energy
      state_class: total_increasing
      unit_of_measurement: kWh
    sensor.shelly_plug_office_energy_usage:
      last_reset: '1970-01-01T00:00:00+00:00'
    sensor.shelly_plug_douche_verwarming_energy_usage:
      last_reset: '1970-01-01T00:00:00+00:00'
    sensor.shelly_plug_badkamer_verwarming_energy_usage:
      last_reset: '1970-01-01T00:00:00+00:00'