#  ____        _        _
# |  _ \  __ _| |_ __ _| |__   __ _ ___  ___
# | | | |/ _` | __/ _` | '_ \ / _` / __|/ _ \
# | |_| | (_| | || (_| | |_) | (_| \__ \  __/
# |____/ \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret influxdb_username
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  precision: s

logbook:
  exclude:
    domains:
      - script
      - sun

recorder:
  db_url: !secret mysql_db_url
  purge_keep_days: 14
  commit_interval: 10
  exclude:
    domains:
      - sun
    entity_globs:
      - sensor.browser_*