# 
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
# The default https://www.home-assistant.io/integrations/stookwijzer/ integration is nice but it's lacking the forecasts, so we're fetching those ourselves from the API.

sensor:
  - platform: rest
    name: Stookwijzer Json Data
    unique_id: stookwijzer_json_data
    resource: "https://data.rivm.nl/geo/alo/wms?service=WMS&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=stookwijzer_v2&LAYERS=stookwijzer_v2&servicekey=82b124ad-834d-4c10-8bd0-ee730d5c1cc8&STYLES=&BUFFER=1&EXCEPTIONS=INIMAGE&info_format=application%2Fjson&feature_count=1&I=17&J=166&WIDTH=256&HEIGHT=256&CRS=EPSG%3A28992&BBOX=44899.52000000008%2C352899.52%2C155000.0000000001%2C463000"
    method: GET
    headers:
      Content-Type: application/json
    json_attributes_path: "$.features[0].properties"
    json_attributes:
      - advies_0
      - advies_6
      - advies_12
      - advies_18
      - definitief_0
      - definitief_6
      - definitief_12
      - definitief_18
    value_template: "{{ as_timestamp(strptime(value_json.features[0].properties.model_runtime, '%d-%m-%Y %H:%M')) }}"

template:
  - sensor:
    - unique_id: stookwijzer_advice_1
      attributes:
        friendly_name: Stookwijzer Advies 1
        time: "{{ states('sensor.stookwijzer_json_data') | int | timestamp_local }}"
        definitive: "{{ state_attr('sensor.stookwijzer_json_data', 'definitief_0') }}"
      name: Stookwijzer Advies 1
      icon: mdi:fire-alert
      state: >
        {% set advice = state_attr('sensor.stookwijzer_json_data', 'advies_0') | int %}
        {% if advice == 0 %}
          code_yellow
        {% elif advice == 1 %}
          code_orange
        {% elif advice == 2 %}
          code_red
        {% else %}
          unknown
        {% endif %}
    - unique_id: stookwijzer_advice_2
      attributes:
        friendly_name: Stookwijzer Advies 2
        time: "{{ ((states('sensor.stookwijzer_json_data') | int) + (6 * 3600)) | timestamp_local }}"
        definitive: "{{ state_attr('sensor.stookwijzer_json_data', 'definitief_6') }}"
      name: Stookwijzer Advies 2
      icon: mdi:fire-alert
      state: >
        {% set advice = state_attr('sensor.stookwijzer_json_data', 'advies_6') | int %}
        {% if advice == 0 %}
          code_yellow
        {% elif advice == 1 %}
          code_orange
        {% elif advice == 2 %}
          code_red
        {% else %}
          unknown
        {% endif %}
    - unique_id: stookwijzer_advice_3
      attributes:
        friendly_name: Stookwijzer Advies 3
        time: "{{ ((states('sensor.stookwijzer_json_data') | int) + (12 * 3600)) | timestamp_local }}"
        definitive: "{{ state_attr('sensor.stookwijzer_json_data', 'definitief_12') }}"
      name: Stookwijzer Advies 3
      icon: mdi:fire-alert
      state: >
        {% set advice = state_attr('sensor.stookwijzer_json_data', 'advies_12') | int %}
        {% if advice == 0 %}
          code_yellow
        {% elif advice == 1 %}
          code_orange
        {% elif advice == 2 %}
          code_red
        {% else %}
          unknown
        {% endif %}
    - unique_id: stookwijzer_advice_4
      attributes:
        friendly_name: Stookwijzer Advies 4
        time: "{{ ((states('sensor.stookwijzer_json_data') | int) + (18 * 3600)) | timestamp_local }}"
        definitive: "{{ state_attr('sensor.stookwijzer_json_data', 'definitief_18') }}"
      name: Stookwijzer Advies 4
      icon: mdi:fire-alert
      state: >
        {% set advice = state_attr('sensor.stookwijzer_json_data', 'advies_18') | int %}
        {% if advice == 0 %}
          code_yellow
        {% elif advice == 1 %}
          code_orange
        {% elif advice == 2 %}
          code_red
        {% else %}
          unknown
        {% endif %}