#  ____
# |  _ \ ___ _ __ ___  ___  _ __  ___
# | |_) / _ \ '__/ __|/ _ \| '_ \/ __|
# |  __/  __/ |  \__ \ (_) | | | \__ \
# |_|   \___|_|  |___/\___/|_| |_|___/
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#

person:
  - name: Rob
    id: rob
    user_id: 56ef6157f087451399aa545f32dc78d3
    device_trackers:
      #- device_tracker.rob_presence
      - device_tracker.iphone_rob
      - device_tracker.iphonedetect_rob
      - device_tracker.apple_watch_rob
  - name: Steffi
    id: steffi
    user_id: 71e44d7d313b4695a8bf51705f7adfc3
    device_trackers:
      #- device_tracker.steffi_presence
      - device_tracker.iphone_steffi
      - device_tracker.iphonedetect_steffi

notify:
  - platform: group
    name: all_phones
    services:
      - service: mobile_app_iphone_rob
      - service: mobile_app_iphone_steffi

homeassistant:
  customize_domain:
    light:
      assumed_state: false
  customize:
    person.rob:
      entity_picture: "/local/images/rob_icon-mirror.png"
    person.steffi:
      entity_picture: "/local/images/steffi_icon.png"
    # device_tracker.rob_presence:
    #   friendly_name: Combined Presence Rob
    # device_tracker.steffi_presence:
    #   friendly_name: Combined Presence Steffi

sensor:
  - platform: history_stats
    name: Cat door today
    entity_id: binary_sensor.motion_sensor_cats_occupancy
    state: "on"
    type: count
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"