#  ____             _
# |  _ \ ___   ___ | |
# | |_) / _ \ / _ \| |
# |  __/ (_) | (_) | |
# |_|   \___/ \___/|_|
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#
template:
  - binary_sensor:
    - unique_id: pool_pump_active
      attributes:
        friendly_name: Pool Pump Active
      state: >
        {{ states('sensor.pool_shelly_3em_active_power_phase_b') | float > 20 }}
  - lock:
    - unique_id: aquadeck_rol_dek
      name: Aquadeck rol dek
      lock:
      - action: switch.turn_on
        target:
          entity_id:
          - switch.pool_deck_lock
      unlock:
      - action: switch.turn_off
        target:
          entity_id:
          - switch.pool_deck_lock
      optimistic: false
      state: "{{ is_state('switch.pool_deck_lock', 'on') }}"
  - sensor:
    - name: "Pool Pump Frequency Level"
      icon: mdi:fan-chevron-down
      unique_id: pool_pump_frequency_level
      state: >
        {% set pumpPower = states('sensor.pool_shelly_3em_active_power_phase_b') | float(default=0) %}
        {% if pumpPower > 800 %}
          FULL (3)
        {% elif pumpPower > 680 and pumpPower < 775 %}
          NORMAL (2)
        {% elif pumpPower > 520 and pumpPower < 620 %}
          LOW (1)
        {% else %}
          OFF
        {% endif %}
    - name: "Pool Deck Status"
      icon: mdi:fit-to-screen
      unique_id: pool_deck_status
      state: >
        {% if is_state('binary_sensor.pool_deck_open', 'on') %}
          Open
        {% elif is_state('binary_sensor.pool_deck_closed', 'on') %}
          Closed
        {% else %}
          Moving
        {% endif %}
    - name: "Pool Heating Temperature Diff"
      icon: mdi:heat-wave
      unique_id: pool_heating_temperature_diff
      attributes:
        friendly_name: Pool Heating Temperature Diff
        has_diff: >
          {{ states('number.pool_fairland_heatpump_target_temperature_heating') | int(default=0) - states('sensor.pool_fairland_heatpump_inlet_water_temperature') | int(default=0) > 0 }}
      state: >
        {{ states('number.pool_fairland_heatpump_target_temperature_heating') | int(default=0) - states('sensor.pool_fairland_heatpump_inlet_water_temperature') | int(default=0) }}

  - light:
    - unique_id: pool_light
      turn_on:
      - action: light.turn_on
        target:
          entity_id:
          - light.pool_lights_pool_lights
      turn_off:
      - action: light.turn_off
        target:
          entity_id:
          - light.pool_lights_pool_lights
      set_level:
      - action: esphome.m5stickc_pool_lights_send_uart_command
        data_template:
          command: PD{{ '%03d' % (brightness / 255 * 100) | float | round(0) }}
      set_rgb:
      - action: esphome.m5stickc_pool_lights_set_color
        data:
          color: PC{{ '%03d' % r }}{{ '%03d' % g }}{{ '%03d' % b }}
      set_effect:
      - action: esphome.m5stickc_pool_lights_send_uart_command
        data_template:
          command: PS{{ effect[:2] }}
      default_entity_id: light.pool_light
      name: Pool Light
      effect_list: '{{ state_attr(''input_select.pool_light_program_options'', ''options'')
        }}'
      effect: '{{ states.input_select.pool_light_program_options.state }}'
      state: '{{ states.light.pool_lights_pool_lights.state }}'

# en/disable all automations for pool
input_boolean:
  enable_pool_automations:
    name: Enable Pool Automations
    icon: mdi:swim

input_button:
  pool_light_program_next:
    name: Pool Light Next Program
    icon: mdi:arrow-right
  pool_light_program_previous:
    name: Pool Light Previous Program
    icon: mdi:arrow-left

input_select:
  pool_light_program_options:
    name: Pool Light Programs
    options:
      - 01. Deep Blue Sea
      - 02. Daylight Blue
      - 03. Sunset
      - 04. Love Is In The Air
      - 05. Forest Spring
      - 06. Think Pink
      - 07. Sunshine
      - 08. Jungle Beach
      - 09. Voodoo
      - 10. Disco
      - 11. Party
      - 12. Warm White
      - 13. Neutral White
      - 14. Sun White
    icon: mdi:palette

sensor:
  # Warmtepomp
  - platform: integration
    source: sensor.pool_shelly_3em_active_power_phase_a
    name: Pool Shelly 3EM Phase A Heatpump Energy Usage
    unique_id: pool_shelly_3em_phase_a_heatpump_energy_usage
    method: left
    unit_prefix: k
    round: 2
  # Pump
  - platform: integration
    source: sensor.pool_shelly_3em_active_power_phase_b
    name: Pool Shelly 3EM Phase B Pump Energy Usage
    unique_id: pool_shelly_3em_phase_b_pump_energy_usage
    method: left
    unit_prefix: k
    round: 2
  # Lights & Deck
  - platform: integration
    source: sensor.pool_shelly_3em_active_power_phase_c
    name: Pool Shelly 3EM Phase C Lights Energy Usage
    unique_id: pool_shelly_3em_phase_c_lights_energy_usage
    method: left
    unit_prefix: k
    round: 2


