#  ____                                
# / ___|  ___ _ __  ___  ___  _ __ ___ 
# \___ \ / _ \ '_ \/ __|/ _ \| '__/ __|
#  ___) |  __/ | | \__ \ (_) | |  \__ \
# |____/ \___|_| |_|___/\___/|_|  |___/
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#

sensor:

- platform: integration
  source: sensor.altherma_power_usage
  name: Altherma Energy Usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.template_altherma_power_usage_secundary
  name: Altherma Energy Usage Secundary
  method: trapezoidal
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.shelly_plug_office_power
  name: Shelly Plug Office Energy Usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_droger_power
  name: Shelly Plug Droger Energy Usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_douche_verwarming_relay_power
  name: Shelly Plug Douche Verwarming Energy Usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_badkamer_verwarming_relay_power
  name: Shelly Plug Badkamer Verwarming Energy Usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_kachel_slaapkamer_power
  name: Shelly Plug Slaapkamer Verwarming Energy Usage
  method: trapezoidal
  unit_prefix: k
  round: 2


- platform: history_stats
  name: Cat door today
  entity_id: binary_sensor.motion_sensor_cats_presence
  state: "on"
  type: count
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

- platform: rest
  name: hass_release_notes
  resource: https://api.github.com/repos/home-assistant/core/releases/latest
  value_template: >
    {{ value_json.name }}
  json_attributes:
    - body
  scan_interval: 21600

- platform: rest
  name: hass_release_notes_rc
  resource: https://api.github.com/repos/home-assistant/core/releases?per_page=1
  value_template: >
    {{ value_json[0].name }}
  json_attributes:
    - body
  scan_interval: 21600

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'

- platform: moon
- platform: uptime

# tracks changes in the lovelace file
- platform: filesize
  file_paths:
    - .storage/lovelace

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot

- platform: unifigateway
  host: !secret router_ip
  port: 443
  version: 'UDMP-unifiOS'
  username: !secret unifi_username
  password: !secret unifi_password
  verify_ssl: false
  monitored_conditions:
    - www
    - lan
    - wan
    - wlan
    - alerts
    - firmware

- platform: command_line
  name: Supervisor updates
  command: 'curl http://supervisor/supervisor/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version,"update_available":.data.update_available,"addons":[.data.addons[] | select(.update_available)]}'''
  value_template: "{{ value_json.addons | length }}"
  unit_of_measurement: pending update(s)
  json_attributes:
  - update_available
  - newest_version
  - current_version
  - addons

- platform: afvalinfo
  resources:
    - gft
    - papier
    - restafval
    - trash_type_today
    - trash_type_tomorrow
  location: goes
  postcode: 4481CP
  streetnumber: 28
  streetnumbersuffix: ""
  dateformat: "%d-%m-%Y"
  locale: "nl"
  timespanindays: 365

# - platform: command_line
#   name: udm_unifios
#   command: !secret udm_unifios
#   value_template: |-
#     {% set json = value_json.data[0] %}
#     {{ json["system-stats"].cpu }}|
#     {{ json.temperatures[1].value | round(1) }}|
#     {{ json["system-stats"].mem }}|
#     {{ ((json.storage[1].used / json.storage[1].size) * 100) | round(1) }}|
#     {{ json.internet }}|
#     {{ json.startup_timestamp | timestamp_custom('%Y-%m-%dT%H:%M:%S') }}|
#     {{ json.displayable_version }}|
#     {{ json.upgradable }}
#   scan_interval: 60