#  ____                                
# / ___|  ___ _ __  ___  ___  _ __ ___ 
# \___ \ / _ \ '_ \/ __|/ _ \| '__/ __|
#  ___) |  __/ | | \__ \ (_) | |  \__ \
# |____/ \___|_| |_|___/\___/|_|  |___/
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#

sensor:

- platform: integration
  source: sensor.altherma_power_usage
  name: Altherma Energy Usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.template_altherma_power_usage_secundary
  name: Altherma Energy Usage Secundary
  method: trapezoidal
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.shelly_plug_office_power
  name: Shelly Plug Office Energy Usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_droger_power
  name: Shelly Plug Droger Energy Usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_douche_verwarming_power
  name: Shelly Plug Douche Verwarming Energy Usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_badkamer_verwarming_power
  name: Shelly Plug Badkamer Verwarming Energy Usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_kachel_slaapkamer_power
  name: Shelly Plug Slaapkamer Verwarming Energy Usage
  method: trapezoidal
  unit_prefix: k
  round: 2


- platform: history_stats
  name: Cat door today
  entity_id: binary_sensor.motion_sensor_cats_presence
  state: "on"
  type: count
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

- platform: rest
  name: hass_release_notes
  resource: https://api.github.com/repos/home-assistant/core/releases/latest
  value_template: >
    {{ value_json.name }}
  json_attributes:
    - body
  scan_interval: 21600

- platform: rest
  name: hass_release_notes_rc
  resource: https://api.github.com/repos/home-assistant/core/releases?per_page=1
  value_template: >
    {{ value_json[0].name }}
  json_attributes:
    - body
  scan_interval: 21600

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'

- platform: moon
- platform: uptime

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot

- platform: unifigateway
  host: !secret router_ip
  port: 443
  version: 'UDMP-unifiOS'
  username: !secret unifi_username
  password: !secret unifi_password
  verify_ssl: false
  monitored_conditions:
    - www
    - lan
    - wan
    - wlan
    - alerts
    - firmware

- platform: afvalinfo
  resources:
    - gft
    - papier
    - restafval
    - trash_type_today
    - trash_type_tomorrow
  location: goes
  postcode: 4481CP
  streetnumber: 28
  streetnumbersuffix: ""
  dateformat: "%d-%m-%Y"
  locale: "nl"
  timespanindays: 365
