#  ____                                
# / ___|  ___ _ __  ___  ___  _ __ ___ 
# \___ \ / _ \ '_ \/ __|/ _ \| '__/ __|
#  ___) |  __/ | | \__ \ (_) | |  \__ \
# |____/ \___|_| |_|___/\___/|_|  |___/
#
# Author: Rob Sonke
# https://github.com/robsonke/hass-config
#

sensor:

- platform: integration
  source: sensor.altherma_power_usage
  name: Altherma Energy Usage
  unique_id: altherma_energy_usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.altherma_power_usage_secundary
  name: Altherma Energy Usage Secundary
  unique_id: altherma_energy_usage_secundary
  method: trapezoidal
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.ix3_charging_power
  name: iX3 Charging Power
  unique_id: ix3_charging_energy
  method: trapezoidal
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.shelly_plug_office_power
  name: Shelly Plug Office Energy Usage
  unique_id: shelly_plug_office_energy_usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_droger_power
  name: Shelly Plug Droger Energy Usage
  unique_id: shelly_plug_droger_energy_usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_douche_verwarming_power
  name: Shelly Plug Douche Verwarming Energy Usage
  unique_id: shelly_plug_douche_verwarming_energy_usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_badkamer_verwarming_power
  name: Shelly Plug Badkamer Verwarming Energy Usage
  unique_id: shelly_plug_badkamer_verwarming_energy_usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_kachel_slaapkamer_power
  name: Shelly Plug Slaapkamer Verwarming Energy Usage
  unique_id: shelly_plug_slaapkamer_verwarming_energy_usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_s_6_meterkast1_power
  name: Shelly Plug Meterkast1 Energy Usage
  unique_id: shelly_plug_meterkast1_energy_usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_s_7_meterkast2_power
  name: Shelly Plug Meterkast2 Energy Usage
  unique_id: shelly_plug_meterkast2_energy_usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_s_8_fridge1_power
  name: Shelly Plug Vriezer Schuur Energy Usage
  unique_id: shelly_plug_vriezer_schuur_energy_usage
  method: trapezoidal
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shelly_plug_koelkast_power
  name: Shelly Plug Koelkast Energy Usage
  unique_id: shelly_plug_koelkast_energy_usage
  method: trapezoidal
  unit_prefix: k
  round: 2

- platform: history_stats
  name: Cat door today
  entity_id: binary_sensor.motion_sensor_cats_presence
  state: "on"
  type: count
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"


- platform: min_max
  name: Downstairs Temperature
  unique_id: downstairs_temperature
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.climate_sensor_kitchen_temperature
    - sensor.climate_sensor_living_temperature
    - sensor.indoor_temperature

- platform: rest
  name: hass_release_notes
  resource: https://api.github.com/repos/home-assistant/core/releases/latest
  value_template: >
    {{ value_json.name }}
  json_attributes:
    - body
  scan_interval: 21600

- platform: rest
  name: hass_release_notes_rc
  resource: https://api.github.com/repos/home-assistant/core/releases?per_page=1
  value_template: >
    {{ value_json[0].name }}
  json_attributes:
    - body
  scan_interval: 21600

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot

- platform: unifigateway
  host: !secret router_ip
  port: 443
  version: 'UDMP-unifiOS'
  username: !secret unifi_username
  password: !secret unifi_password
  verify_ssl: false
  monitored_conditions:
    - www
    - lan
    - wan
    - wlan
    - alerts
    - firmware

- platform: afvalinfo
  resources:
    - gft
    - papier
    - restafval
    - trash_type_today
    - trash_type_tomorrow
  location: goes
  postcode: 4481CP
  streetnumber: 28
  streetnumbersuffix: ""
  dateformat: "%d-%m-%Y"
  locale: "nl"
  timespanindays: 365

- platform: rest
  name: Tibber prices
  unique_id: tibber_prices
  resource: https://api.tibber.com/v1-beta/gql
  method: POST
  scan_interval: 60
  payload: '{ "query": "{ viewer { homes { currentSubscription { priceInfo { today { total startsAt } tomorrow { total startsAt }}}}}}" }'
  json_attributes_path: "$.data.viewer.homes[0].currentSubscription.priceInfo"
  json_attributes:
    - today
    - tomorrow
  value_template: Ok
  headers:
    Authorization: !secret tibber_access_token
    Content-Type: application/json
    User-Agent: REST

- platform: nordpool_diff
  nordpool_entity: sensor.nordpool_kwh_nl_eur_3_10_009


# Lots of power sensors based on powercalc for existing entities
# TODO
# - nest mini's
# - chargers
# - pump

# moved car charging to a separate entity since it blows up the groups
- platform: powercalc
  entity_id: sensor.ix3_charging_status
  name: iX3 Charging
  fixed:
    power: "{{ iif(is_state('binary_sensor.ix3_charging_status', 'on'), 10000, 0) }}"
- platform: powercalc
  create_group: All Powercalc Entities
  entities:
    - create_group: All Housekeeping Entities
      entities:
        - entity_id: vacuum.sjorsje
          fixed:
            states_power:
              charging: 28
              docked: >
                {%- if is_state('vacuum.sjorsje', 'docked') and states('sensor.sjorsje_battery_level') | int(default=0) < 100 %} 28 {%- else %} 3.6 {%- endif %}
              paused: 0
              cleaning: 0
        # Fake power entities
        - name: Quooker
          unique_id: quooker
          daily_fixed_energy:
            value: 10
            unit_of_measurement: W
        - name: Air Quality
          unique_id: air_quality
          daily_fixed_energy:
            value: 20
            unit_of_measurement: W
    - create_group: All Media
      # this is also part of sensor.all_media_player_power automatically
      entities:
        # See https://support.sonos.com/s/article/256?language=en_US
        - entity_id: media_player.living_room
          name: Sonos Woonkamer
          fixed:
            states_power:
              playing: 12
              paused: 2.2
              idle: 2.2
        - entity_id: media_player.eetkamer
          name: Sonos Eetkamer
          fixed:
            states_power:
              playing: 12
              paused: 2.2
              idle: 2.2
        - create_group: TV Woonkamer Group
          entities:
          - entity_id: media_player.tv_room
            name: Sonos TV
            fixed:
              # Sonos Beam Gen 2
              # 6,3W
              power: 6.3
              states_power:
                # 9W
                playing: 9
          - entity_id: media_player.samsung_qn95aa_55_tv
            standby_power: 0.5
            fixed:
              states_power:
                power: 103
                "on": 103
                idle: 103
                paused: 103
                playing: 103
        - entity_id: media_player.samsung_7_series_43
          standby_power: 0.5
          fixed:
            states_power:
              power: 115
              "on": 115
              idle: 115
              paused: 115
              playing: 115
    # Most of the lights are auto discovered
    - create_group: All Manual Lights
      entities:
        - entity_id: light.office_lights
          linear:
            min_power: 0.5
            # 6 * 5.5W
            max_power: 33
        - entity_id: light.kitchencabin_light
          linear:
            # 2 * 5.5W
            min_power: 0.5
            max_power: 11
        - entity_id: light.kitchen_light
          linear:
            # 5 * 5.5W
            min_power: 0.5
            max_power: 27.5
        - entity_id: light.kitchendesk_light
          linear:
            # 5 * 8W
            min_power: 0.5
            max_power: 40
            
        - entity_id: light.dining_light
          linear:
            # 5 * 5.5W
            min_power: 0.5
            max_power: 27.5
        - entity_id: light.diningtable_light
          linear:
            # 2 * 9W
            min_power: 0.5
            max_power: 18
        # Living Room
        - entity_id: light.livingback_light
          linear:
            # 4 * 5.5W
            min_power: 0.5
            max_power: 22
        - entity_id: light.livingfront_light
          linear:
            # 4 * 5.5W
            min_power: 0.5
            max_power: 22
        - entity_id: light.zwave_light_corner_level
          linear:
            # 3 * 3.8W
            min_power: 0.5
            max_power: 11.4
        - entity_id: light.zwave_light_couch_level
          linear:
            # 3 * 5W
            min_power: 0.5
            max_power: 15
        # Hall and upstairs
        - entity_id: light.hal
          linear:
            # 5 * 5.5W
            min_power: 0.5
            max_power: 27.5
        - entity_id: light.overloop
          linear:
            # 4 * 5.5W
            min_power: 0.5
            max_power: 22
        - entity_id: light.logeerkamer
          linear:
            # 4 * 5.5W
            min_power: 0.5
            max_power: 22
        - entity_id: light.zolder
          linear:
            # 4 * 5.5W
            min_power: 0.5
            max_power: 22
        - entity_id: light.slaapkamer_eva
          linear:
            # 4 * 5.5W
            min_power: 0.5
            max_power: 22
        - entity_id: light.badkamer
          linear:
            # 5 * 5.5W
            min_power: 0.5
            max_power: 27.5
        - entity_id: light.hoofdslaapkamer
          linear:
            # 5 * 5.5W
            min_power: 0.5
            max_power: 27.5
        - entity_id: light.inloopkast
          linear:
            # 4 * 5.5W
            min_power: 0.5
            max_power: 22
        - entity_id: light.douche
          linear:
            # 2 * 5.5W
            min_power: 0.5
            max_power: 11
        # Garden
        - entity_id: light.garden_lantern_light1
          linear:
            # 1 * 7W
            min_power: 0.5
            max_power: 7
        - entity_id: light.garden_lantern_light2
          linear:
            # 1 * 7W
            min_power: 0.5
            max_power: 7
        - entity_id: light.garden_lantern_light3
          linear:
            # 1 * 7W
            min_power: 0.5
            max_power: 7
        - entity_id: light.garden_light
          linear:
            # 4 * cubes (12W)
            # 2 * wall (5W)
            min_power: 0.5
            max_power: 58
