name: Validate Home Assistant Config

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Lint Code Base
        uses: github/super-linter@v7
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_YAML: true
          FILTER_REGEX_EXCLUDE: '^(custom_components/|blueprints/|esphome/custom_components/|esphome/archive/|www/|.vscode/)'
          DISABLE_LINTERS: >
            CHECKOV  
            GITHUB_ACTIONS
  home-assistant:
    name: "Home Assistant Core ${{ matrix.version }} Configuration Check"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["stable"]
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v5
      - name: 🚀 Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1
        with:
          path: "."
          secrets: .stub/fakesecrets.yaml
          version: "${{ matrix.version }}"
